project:
  type: book

book:
  title: "Evolutionary history and ecology context shape mixed paternity across birds"
  author: "Aneta Arct<sup>1,2*</sup>, Santiago Ortega<sup>1</sup>, Szymon M. Drobniak<sup>2</sup>, Agnieszka Gudowska<sup>3</sup>, Karolina Skorb<sup>4</sup>, Monika Gronowska<sup>5</sup>, Magdalena Zagalska-Neubauer<sup>5</sup>, Michael Griesser<sup>6</sup>, Malgorzata Lagisz<sup>1,&dagger;</sup>, Shinichi Nakagawa<sup>1,&dagger;</sup>"
  chapters:
    - index.qmd
    - 01_analysis_metadata.qmd
    - 02_data_preparation.qmd
    - 03_overall_model.qmd
    - 04_methodological_moderators.qmd
    - 05_breeding_system_moderators.qmd
    - 06_biological_moderators.qmd
    - 07_figures.qmd

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    css: styles.css
