project:
  type: book

book:
  title: "Explaining variation in mixed paternity across birds: a global comparative meta-analysis"
  author: "Aneta Arct et al. 2026"
  chapters:
    - index.qmd
    - 01_analysis_metadata.qmd
    - 02_data_preparation.qmd
    - 03_overall_model.qmd
    - 04_methodological_moderators.qmd
    - 05_biological_moderators.qmd
    - 06_full_model.qmd
    - 07_figures.qmd

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    css: styles.css
